CREATE TABLE Roles(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
RoleName NVARCHAR(50) NOT NULL
);

CREATE TABLE Users(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Username VARCHAR(16) NOT NULL,
Password VARCHAR(16) NOT NULL,
FullName NVARCHAR(100) NOT NULL,
ContactInfo NVARCHAR(100),
RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id)
);

CREATE TABLE ApplianceCategory(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ApplianceCategoryName NVARCHAR(50) NOT NULL
);

CREATE TABLE ApplianceStatuses(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
StatusName NVARCHAR(50) NOT NULL
);

CREATE TABLE Owners(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
OwnerName NVARCHAR(100) NOT NULL,
ContactInfo NVARCHAR(100)
);

CREATE TABLE Appliance(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES ApplianceCategory(Id),
StatusId INT NOT NULL FOREIGN KEY REFERENCES ApplianceStatuses(Id),
ApplianceName NVARCHAR(100) NOT NULL,
ApplianceAddress NVARCHAR(150) NOT NULL,
ApplianceOwnerId INT NOT NULL FOREIGN KEY REFERENCES Owners(Id),
InstalledSince DATE,
NextExamination DATE,
SerialNumber NVARCHAR(100),
Notes NVARCHAR(255)
);

CREATE TABLE ApplianceCheck(
UserId INT FOREIGN KEY REFERENCES Users(Id),
ApplianceId INT FOREIGN KEY REFERENCES Appliance(Id),
CheckDate DATE NOT NULL,
PRIMARY KEY (UserId, ApplianceId)
);

CREATE TABLE ToolCategory(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ToolCategoryName NVARCHAR(50) NOT NULL
);

CREATE TABLE ToolManufacturerType(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ManufacturerTypeName NVARCHAR(100) NOT NULL
);

CREATE TABLE ToolManufacturer(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ManufacturerName NVARCHAR(100) NOT NULL,
ManufacturerTypeId INT NOT NULL FOREIGN KEY REFERENCES ToolManufacturerType(Id),
ContactInfo NVARCHAR(100),
RepresentativeName NVARCHAR(100)
);

CREATE TABLE Tool(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES ToolCategory(Id),
ModelName NVARCHAR(100) NOT NULL,
OperatingSince DATE,
NextExamination DATE,
DecomissionedSince DATE,
ManufacturerId INT NOT NULL FOREIGN KEY REFERENCES ToolManufacturer(Id),
SerialNumber NVARCHAR(100),
Notes NVARCHAR(255)
);

CREATE TABLE ToolCheck(
UserId INT FOREIGN KEY REFERENCES Users(Id),
ToolId INT FOREIGN KEY REFERENCES Tool(Id),
CheckDate DATE NOT NULL,
PRIMARY KEY(UserId, ToolId)
);

CREATE TABLE DistributionStatuses(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
StatusName NVARCHAR(50) NOT NULL
);

CREATE TABLE DistributionArz(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(250) NOT NULL,
Length DECIMAL(8,2) NOT NULL,
StatusId INT NOT NULL FOREIGN KEY REFERENCES DistributionStatuses(Id)
);