CREATE TABLE Roles(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
RoleName NVARCHAR(50) NOT NULL
);

CREATE TABLE Users(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Username VARCHAR(16) NOT NULL,
Password VARCHAR(16) NOT NULL,
FullName NVARCHAR(100) NOT NULL,
RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id)
);

CREATE TABLE Category(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CategoryName NVARCHAR(50) NOT NULL
);

CREATE TABLE Statuses(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
StatusName NVARCHAR(50) NOT NULL
);

CREATE TABLE Owners(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
OwnerName NVARCHAR(100) NOT NULL,
ContactInfo NVARCHAR(100)
);

CREATE TABLE Appliance(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES Category(Id),
StatusId INT NOT NULL FOREIGN KEY REFERENCES Statuses(Id),
ApplianceName NVARCHAR(100) NOT NULL,
ApplianceAddress NVARCHAR(150) NOT NULL,
ApplianceOwnerId INT NOT NULL FOREIGN KEY REFERENCES Owners(Id),
InstalledSince DATE,
NextExamination DATE,
SerialNumber NVARCHAR(100),
Notes NVARCHAR(255)
);

CREATE TABLE ApplianceCheck(
UserId INT FOREIGN KEY REFERENCES Users(Id),
ApplianceId INT FOREIGN KEY REFERENCES Appliance(Id),
CheckDate DATE NOT NULL,
PRIMARY KEY (UserId, ApplianceId)
);