//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gas_appliances.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplianceCheck
    {
        public int UserId { get; set; }
        public int ApplianceId { get; set; }
        public System.DateTime CheckDate { get; set; }
    
        public virtual Appliance Appliance { get; set; }
        public virtual Users Users { get; set; }
    }
}
