//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gas_appliances.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appliance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appliance()
        {
            this.ApplianceCheck = new HashSet<ApplianceCheck>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int StatusId { get; set; }
        public string ApplianceName { get; set; }
        public string ApplianceAddress { get; set; }
        public int ApplianceOwnerId { get; set; }
        public Nullable<System.DateTime> InstalledSince { get; set; }
        public Nullable<System.DateTime> NextExamination { get; set; }
        public string SerialNumber { get; set; }
        public string Notes { get; set; }
    
        public virtual Owners Owners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplianceCheck> ApplianceCheck { get; set; }
        public virtual Category Category { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
