//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gas_appliances.AuxClasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gas_applliancesEntities : DbContext
    {
        public gas_applliancesEntities()
            : base("name=gas_applliancesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appliance> Appliance { get; set; }
        public virtual DbSet<ApplianceCheck> ApplianceCheck { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tool> Tool { get; set; }
        public virtual DbSet<ToolCategory> ToolCategory { get; set; }
        public virtual DbSet<ToolCheck> ToolCheck { get; set; }
        public virtual DbSet<ToolManufacturer> ToolManufacturer { get; set; }
        public virtual DbSet<ToolManufacturerType> ToolManufacturerType { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
