//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gas_appliances.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolManufacturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolManufacturer()
        {
            this.Tool = new HashSet<Tool>();
        }
    
        public int Id { get; set; }
        public string ManufacturerName { get; set; }
        public int ManufacturerTypeId { get; set; }
        public string ContactInfo { get; set; }
        public string RepresentativeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tool { get; set; }
        public virtual ToolManufacturerType ToolManufacturerType { get; set; }
    }
}
