//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gas_appliances.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tool()
        {
            this.ToolCheck = new HashSet<ToolCheck>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string ModelName { get; set; }
        public Nullable<System.DateTime> OperatingSince { get; set; }
        public Nullable<System.DateTime> NextExamination { get; set; }
        public Nullable<System.DateTime> DecomissionedSince { get; set; }
        public int ManufacturerId { get; set; }
        public string SerialNumber { get; set; }
        public string Notes { get; set; }
    
        public virtual ToolCategory ToolCategory { get; set; }
        public virtual ToolManufacturer ToolManufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolCheck> ToolCheck { get; set; }
    }
}
