//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gas_appliances.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolCheck
    {
        public int UserId { get; set; }
        public int ToolId { get; set; }
        public System.DateTime CheckDate { get; set; }
    
        public virtual Tool Tool { get; set; }
        public virtual Users Users { get; set; }
    }
}
